### PR TITLE
Add some missing links in doc/pazpar2_conf

### PR DESCRIPTION
**Pull request by dcrossleyau**

### CODE REVIEW

**Comment by MikeTaylor** [comment]
I looked over the changes, and they all look good to me. But I am reluctant to accept the pull because the Travis CI failed. On the other hand, that failure was in test_termlist_block.sh, which is surely no affected by this pull, so it's probably an unrelated and pre-existing issue. Adam, what do you think?

**Comment by dcrossleyau** [comment]
Strange. Doing 'make check' passes all of those tests on my local OSX.

I notice that Travis passes on the Debian systems.

For the other pull today (#11) which happened soon after, all tests did pass on OSX.

(Different issue: We need to wait a lot longer for the OSX Travis build.)

**Comment by MikeTaylor** [comment]
Just to be clear -- since I'm not familiar with Travis and suchlike -- you're saying the successful tests run on the commit for pull #11 were run on code that included the commits for #10? If so, then we can conclude that the failure on #10 was transitory, and I'll go ahead with the merge.

**Comment by dcrossleyau** [comment]
Er, sorry, i was not clear (and also a Travis newbie). No, the pull #11 does not include the #10 stuff. My local build here on Mac did succeed 'make check', and of course that has both sets of commits. Not sure why i mentioned #11 on OSX :-)

**Comment by MikeTaylor** [comment]
OK, if your local build has both commits and is working OK, I'm going to go ahead and merge. If anything goes wrong, we'll find out soon enough!

**Pull request merged**
